CREATE TABLE [Business].[ImagesPosted_Comment](
	[ID] [int] NOT NULL,
	[Comments] [text] NOT NULL,
	[Commented_By] [varchar](20) NOT NULL


INSERT INTO Personal.ImagesPosted_Comment
VALUES (2,	'Integer a nibh.',	'BU21'),
        (2,	'In hac habitasse platea dictumst.',	'BU4'),
        (2,	'Donec ut mauris eget massa tempor convallis.',	'PU12'),
        (2,	'In hac habitasse platea dictumst',	'BU10'),
        (2,	'Morbi non quam nec dui luctus rutrum.',	'BU15'),
        (3,	'Aenean lectus.',	'PU12'),
        (3,	'Mauris ullamcorper purus sit amet nulla.',	'PU20'),
        (4,	'Nunc nisl.',	'PU18'),
        (4,	'In blandit ultrices enim.',	'BU10'),
        (4,	'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.',	'PU24'),
        (4,	'Aliquam non mauris.',	'PU5'),
        (5,	'Suspendisse potenti.'	,'PU4'),
        (5,	'Nam dui.',	'PU1'),
        (5,	'Maecenas tincidunt lacus at velit.',	'BU3'),
        (5,	'Vestibulum sed magna at nunc commodo placerat',	'PU25'),
        (5,	'Nunc rhoncus dui vel sem.',	'PU25'),
        (6,	'Ut tellus.',	'PU19'),
        (6,	'Mauris lacinia sapien quis libero.',	'PU18'),
        (6,	'Donec quis orci eget orci vehicula condimentum.',	'BU13'),
        (6,	'Sed accumsan felis.',	'BU22'),
        (6,	'Duis bibendum',	'PU17'),
        (7,	'Etiam faucibus cursus urna.',	'BU12'),
        (8,	'Integer ac leo.', 'BU17'),
        (8,	'Cras pellentesque volutpat dui.',	'PU14'),
        (8,	'Donec posuere metus vitae ipsum.',	'PU11'),
        (8,	'Aenean fermentum.',	'PU20'),
        (8,	'Nunc nisl.',	'PU8'),
        (9,	'Integer tincidunt ante vel ipsum.',	'BU21'),
        (9,	'Duis ac nibh',	'PU15'),
        (9,	'Maecenas pulvinar lobortis est.',	'PU21'),
        (9,	'Maecenas rhoncus aliquam lacus.',	'BU6'),
        (10,	'Nulla justo.',	'BU4'),
        (10,	'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.',	'PU14'),
        (10,	'Suspendisse accumsan tortor quis turpis.',	'BU20'),
        (10,	'Nulla justo.',	'PU20'),
        (10,	'Morbi non quam nec dui luctus rutrum.',	'PU13'),
        (11,	'Nulla justo.',	'PU3'),
        (11,	'Integer non velit.',	'BU24'),
        (11,	'Fusce consequat.',	'PU4'),
        (12,	'Aenean fermentum.',	'BU5'),
        (13,	'Fusce consequat.',	'BU8'),
        (13,	'Nunc purus.',  'BU25'),
        (13,	'In hac habitasse platea dictumst.',	'PU6'),
        (13,	'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.',	'BU8'),
        (13,	'Phasellus id sapien in sapien iaculis congue.',	'PU3'),
        (15,	'In blandit ultrices enim.',	'PU23'),
        (15,	'Aliquam quis turpis eget elit sodales scelerisque.',	'BU1'),
        (15,	'Suspendisse accumsan tortor quis turpis.',	'BU19'),
        (15,	'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.','BU14'),
        (15,	'Pellentesque ultrices mattis odio.',	'BU19'),
        (16,	'Donec ut mauris eget massa tempor convallis.',	'BU8'),
        (16,	'Aliquam non mauris.',	'BU2'),
        (16,	'Donec ut dolor.',	'PU23'),
        (16,	'Donec vitae nisi.','BU11'),
        (16,	'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',	'BU11'),
        (17,	'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',	'BU11'),
        (17,	'Vestibulum rutrum rutrum neque',	'BU6'),
        (17,	'Aliquam erat volutpat.',	'BU21'),
        (17,	'Nulla ut erat id mauris vulputate elementum.',	'PU13'),
        (18,	'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices .',	'BU7'),
        (18,	'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',	'PU2'),
        (18,	'Etiam pretium iaculis justo.',	'PU17'),
        (19,	'Vivamus vestibulum sagittis sapien.',	'PU12'),
        (19,	'Integer non velit.',	'BU7'),
        (19,	'Aliquam sit amet diam in magna bibendum imperdiet.',	'BU23'),
        (19,	'Praesent id massa id nisl venenatis lacinia.',	'PU24'),
        (20,	'Duis ac nibh.',	'BU15'),
        (20,	'Vivamus vestibulum sagittis sapien.',	'BU16'),
        (20,	'In sagittis dui vel nisl.',	'BU18'),
        (20,	'In est risus, auctor sed, tristique in, tempus sit amet, sem.',	'BU5'),
        (20,	'Nam nulla.',	'BU14'),
        (21,	'Vestibulum sed magna at nunc commodo placerat.',	'PU9'),
        (21,	'Vivamus vel nulla eget eros elementum pellentesque.',	'PU3'),
        (23,	'Morbi non quam nec dui luctus rutrum.',	'BU23'),
        (23,	'Morbi a ipsum.',	'BU16'),
        (23,	'In hac habitasse platea dictumst',	'PU25'),
        (23,	'Morbi non quam nec dui luctus rutrum.',	'PU12'),
        (24,	'Aenean lectus.',	'BU14'),
        (25,	'Mauris ullamcorper purus sit amet nulla.',	'BU17'),
        (25,	'Nunc nisl.',	'BU5'),
        (26,	'In blandit ultrices enim.',	'BU19'),
        (26,	'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.',	'BU2'),
        (26,	'Aliquam non mauris.',	'BU9'),
        (26,	'Suspendisse potenti.'	,'PU20'),
        (26,	'Nam dui.',	'BU1'),
        (27,	'Maecenas tincidunt lacus at velit.',	'PU20'),
        (27,	'Vestibulum sed magna at nunc commodo placerat',	'PU13'),
        (27,	'Nunc rhoncus dui vel sem.',	'PU1'),
        (27,	'Ut tellus.',	'BU11'),
        (29,	'Mauris lacinia sapien quis libero.',	'PU5'),
        (29,	'Donec quis orci eget orci vehicula condimentum.',	'PU20'),
        (29,	'Sed accumsan felis.',	'BU24'),
        (29,	'Duis bibendum',	'BU13'),
        (29,	'Etiam faucibus cursus urna.',	'PU25'),
        (30,	'Integer ac leo.', 'PU13'),
        (30,	'Cras pellentesque volutpat dui.',	'BU27'),
        (30,	'Donec posuere metus vitae ipsum.',	'PU2'),
        (30,	'Aenean fermentum.',	'BU6'),
        (30,	'Nunc nisl.',	'BU11'),
        (31,	'Integer tincidunt ante vel ipsum.',	'PU18'),
        (31,	'Duis ac nibh',	'BU20'),
        (31,	'Maecenas pulvinar lobortis est.',	'PU14'),
        (31,	'Maecenas rhoncus aliquam lacus.',	'BU9'),
        (32,	'Nulla justo.',	'BU6'),
        (32,	'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.',	'PU20'),
        (32,	'Suspendisse accumsan tortor quis turpis.',	'PU2'),
        (33,	'Nulla justo.',	'BU15'),
        (33,	'Morbi non quam nec dui luctus rutrum.',	'PU15'),
        (33,	'Nulla justo.',	'BU4'),
        (33,	'Integer non velit.',	'BU13'),
        (33,	'Fusce consequat.',	'BU21'),
        (34,	'Aenean fermentum.',	'BU12'),
        (34,	'Fusce consequat.',	'BU11'),
        (35,	'Nunc purus.',  'PU7'),
        (35,	'In hac habitasse platea dictumst.',	'BU2'),
        (36,	'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.',	'PU4'),
        (36,	'Phasellus id sapien in sapien iaculis congue.',	'BU16'),
        (36,	'In blandit ultrices enim.',	'BU18'),
        (37,	'Aliquam quis turpis eget elit sodales scelerisque.',	'BU7'),
        (37,	'Suspendisse accumsan tortor quis turpis.',	'PU21'),
        (37,	'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.','PU5'),
        (37,	'Pellentesque ultrices mattis odio.',	'BU6'),
        (37,	'Donec ut mauris eget massa tempor convallis.',	'PU2'),
        (38,	'Aliquam non mauris.',	'BU23'),
        (38,	'Donec ut dolor.',	'BU5'),
        (38,	'Donec vitae nisi.','PU7')
        

