CREATE TABLE [Business].[VideosPosted_Comment](
	[ID] [int] NOT NULL,
	[Comments] [text] NOT NULL,
	[Commented_By] [varchar](50) NOT NULL


insert into Business.VideosPosted_Comment  values (1, 'Etiam vel augue.', 'PU10');
insert into Business.VideosPosted_Comment  values (2, 'Morbi non quam nec dui luctus rutrum.', 'PU3');
insert into Business.VideosPosted_Comment  values (3, 'Duis bibendum.', 'BU25');
insert into Business.VideosPosted_Comment  values (4, 'Etiam pretium iaculis justo.', 'PU22');
insert into Business.VideosPosted_Comment  values (5, 'Vivamus in felis eu sapien cursus vestibulum.', 'PU6');
insert into Business.VideosPosted_Comment  values (6, 'Morbi vel lectus in quam fringilla rhoncus.', 'PU5');
insert into Business.VideosPosted_Comment  values (7, 'Vestibulum ante ipsum primis in faucibus orci lus accumsan odio.', 'PU1');
insert into Business.VideosPosted_Comment  values (8, 'Morbi vestibulum,usto, nec condimentum neque sapien placerat ante.', 'BU2');
insert into Business.VideosPosted_Comment  values (9, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'PU23');
insert into Business.VideosPosted_Comment  values (10, 'Ut at dolor quis odio consequat varius.', 'BU17');
insert into Business.VideosPosted_Comment  values (11, 'Integer aliquet, massa , vel accumsan tellus nisi eu orci.', 'BU5');
insert into Business.VideosPosted_Comment  values (12, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'BU8');
insert into Business.VideosPosted_Comment  values (13, 'Nulla mollis molestie lorem.', 'BU5');
insert into Business.VideosPosted_Comment  values (14, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'BU19');
insert into Business.VideosPosted_Comment  values (15, 'Integer tincidunt ante vel ipsum.', 'PU15');
insert into Business.VideosPosted_Comment  values (16, 'Ut at dolor quis odio consequat varius.', 'PU23');
insert into Business.VideosPosted_Comment  values (17, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'BU7');
insert into Business.VideosPosted_Comment  values (18, 'Maecenas rhoncus aliquam lacus.', 'BU16');
insert into Business.VideosPosted_Comment  values (19, 'Phasellus in felis.', 'PU15');
insert into Business.VideosPosted_Comment  values (20, 'Aenean sit amet justo.', 'BU2');
insert into Business.VideosPosted_Comment  values (21, 'Aliquam quis turpis eget elit sodales scelerisque.', 'BU6');
insert into Business.VideosPosted_Comment  values (22, 'Vestibulum ante  sit amet lobortis sapien sapien non mi.', 'PU19');
insert into Business.VideosPosted_Comment  values (23, 'Etiam faucibus cursus urna.', 'BU18');
insert into Business.VideosPosted_Comment  values (24, 'Etiam justo.', 'BU16');
insert into Business.VideosPosted_Comment  values (25, 'Donec ut mauris eget massa tempor convallis.', 'PU5');
insert into Business.VideosPosted_Comment  values (26, 'Duis mattis egestas metus.', 'PU25');
insert into Business.VideosPosted_Comment  values (27, 'Cum sociis natoque penatibuascetur ridiculus mus.', 'BU2');
insert into Business.VideosPosted_Comment  values (28, 'Pellentesque viverra pede ac diam.', 'BU22');
insert into Business.VideosPosted_Comment  values (29, 'Suspendisse ornare consequat lectus.', 'PU10');
insert into Business.VideosPosted_Comment  values (30, 'Donec ut mauris eget massa tempor convallis.', 'PU1');
insert into Business.VideosPosted_Comment  values (31, 'Etiam vel augue.', 'BU3');
insert into Business.VideosPosted_Comment  values (32, 'Vestibulum rutrum rutrum neque.', 'BU5');
insert into Business.VideosPosted_Comment  values (33, 'Suspendisse ornare consequat lectus.', 'BU9');
insert into Business.VideosPosted_Comment  values (34, 'Sed vel enim sit amet nunc viverra dapibus.', 'PU24');
insert into Business.VideosPosted_Comment  values (35, 'Suspendisse potenti.', 'PU9');
insert into Business.VideosPosted_Comment  values (36, 'Duis ac nibh.', 'BU17');
insert into Business.VideosPosted_Comment  values (37, 'Nam ultricesulla elit ac nulla.', 'BU2');
insert into Business.VideosPosted_Comment  values (38, 'Etiam pretium iaculis justo.', 'BU4');
insert into Business.VideosPosted_Comment  values (39, 'Duis consequat dui nec nisi volutpat eleifend.', 'BU12');
insert into Business.VideosPosted_Comment  values (40, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'PU20');
insert into Business.VideosPosted_Comment  values (41, 'Aliquam quis turpis eget elit sodales scelerisque.', 'BU8');
insert into Business.VideosPosted_Comment  values (42, 'Fusce posuere felis sed lacus.', 'PU12');
insert into Business.VideosPosted_Comment  values (43, 'Donec posuere metus vitae ipsum.', 'PU13');
insert into Business.VideosPosted_Comment  values (44, 'Vestibulum ac est lacinia nisi venenatis tristique.', 'BU2');
insert into Business.VideosPosted_Comment  values (45, 'Cum sociis naetur ridiculus mus.', 'BU22');
insert into Business.VideosPosted_Comment  values (46, 'Aenean auctor gravida sem.', 'BU14');
insert into Business.VideosPosted_Comment  values (47, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'PU1');
insert into Business.VideosPosted_Comment  values (48, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'PU10');
insert into Business.VideosPosted_Comment  values (49, 'Suspendisse potenti.', 'PU3');
insert into Business.VideosPosted_Comment  values (50, 'Integer aliquet, massa id lobortis convali eu orci.', 'PU22');
insert into Business.VideosPosted_Comment  values (51, 'Pellentesque ultrices mattis odio.', 'BU14');
insert into Business.VideosPosted_Comment  values (52, 'Aliquam augue quam, solt, rutrum at, lorem.', 'PU9');
insert into Business.VideosPosted_Comment  values (53, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'PU15');
insert into Business.VideosPosted_Comment  values (54, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'BU8');
insert into Business.VideosPosted_Comment  values (55, 'Mauris ullamcorper purus sit amet nulla.', 'PU21');
insert into Business.VideosPosted_Comment  values (56, 'Cras in purus eu magna vulputate luctus.', 'BU4');
insert into Business.VideosPosted_Comment  values (57, 'Nulla suscipit ligula in lacus.', 'PU4');
insert into Business.VideosPosted_Comment  values (58, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'PU5');
insert into Business.VideosPosted_Comment  values (59, 'Mauris sit amet eros.', 'BU12');
insert into Business.VideosPosted_Comment  values (60, 'Vestibulum rutrum rutrum neque.', 'PU14');
insert into Business.VideosPosted_Comment  values (61, 'Nulla suscipit ligula in lacus.', 'BU4');
insert into Business.VideosPosted_Comment  values (62, 'Nam congue, risus semper pouis orci.', 'PU2');
insert into Business.VideosPosted_Comment  values (63, 'Integer a nibh.', 'BU18');
insert into Business.VideosPosted_Comment  values (64, 'Donec ut dolor.', 'PU2');
insert into Business.VideosPosted_Comment  values (65, 'Phasellus id sapien in sapien iaculis congue.', 'BU6');
insert into Business.VideosPosted_Comment  values (66, 'Suspendisse potenti.', 'PU15');
insert into Business.VideosPosted_Comment  values (67, 'Integer ac leo.', 'BU6');
insert into Business.VideosPosted_Comment  values (68, 'Sed sagittis.', 'PU18');
insert into Business.VideosPosted_Comment  values (69, 'Morbi ut odio.', 'BU18');
insert into Business.VideosPosted_Comment  values (70, 'Fusce posuere felis sed lacus.', 'PU15');
insert into Business.VideosPosted_Comment  values (71, 'Nulla ut erat id mauris vulputate elementum.', 'BU4');
insert into Business.VideosPosted_Comment  values (72, 'Integer ac neque.', 'PU14');
insert into Business.VideosPosted_Comment  values (73, 'Integer aliquet, tellus nisi eu orci.', 'BU17');
insert into Business.VideosPosted_Comment  values (74, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'BU7');
insert into Business.VideosPosted_Comment  values (75, 'Morbi porttitor lorem id ligula.', 'BU6');
insert into Business.VideosPosted_Comment  values (76, 'Aliquam quis turpis eget elit sodales scelerisque.', 'PU6');
insert into Business.VideosPosted_Comment  values (77, 'Praesent lectus.', 'PU4');
insert into Business.VideosPosted_Comment  values (78, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'BBU22');
insert into Business.VideosPosted_Comment  values (79, 'Sed vel enim sit amet nunc viverra dapibus.', 'BU23');
insert into Business.VideosPosted_Comment  values (80, 'Nam dui.', 'PU21');
insert into Business.VideosPosted_Comment  values (81, 'Curabitur convallis.', 'PU17');
insert into Business.VideosPosted_Comment  values (82, 'In hac habitasse platea dictumst.', 'BU11');
insert into Business.VideosPosted_Comment  values (83, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'BU25');
insert into Business.VideosPosted_Comment  values (84, 'Nunc rhoncus dui vel sem.', 'PU17');
insert into Business.VideosPosted_Comment  values (85, 'Sed vel enim sit amet nunc viverra dapibus.', 'PU5');
insert into Business.VideosPosted_Comment  values (86, 'Morbi non quam nec dui luctus rutrum.', 'BU8');
insert into Business.VideosPosted_Comment  values (87, 'Nunc rhoncus dui vel sem.', 'PU16');
insert into Business.VideosPosted_Comment  values (88, 'Mauris ullamcorper purus sit amet nulla.', 'PU16');
insert into Business.VideosPosted_Comment  values (89, 'Vestibulum ante ipsum primis in faucibus orci luuam.', 'PU11');
insert into Business.VideosPosted_Comment  values (90, 'Phasellus sit amet erat.', 'PU14');
insert into Business.VideosPosted_Comment  values (91, 'Duis enim blandit mi, in porttitor pede justo eu massa.', 'PU25');
insert into Business.VideosPosted_Comment  values (92, 'Cras in purus eu magna vulputate luctus.', 'PU6');
insert into Business.VideosPosted_Comment  values (93, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'PI21');
insert into Business.VideosPosted_Comment  values (94, 'Nulla nisl.', 'BU22');
insert into Business.VideosPosted_Comment  values (95, 'Suspendisse ornare consequat lectus.', 'PU1');
insert into Business.VideosPosted_Comment  values (96, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'BBU14');
insert into Business.VideosPosted_Comment  values (97, 'Duis bibendum, felis sed intitor pede justo eu massa.', 'BU23');
