CREATE TABLE [Personal].[Storytext_Activities](
	[ID] [int] NOT NULL,
	[Reply] [text] NOT NULL,
	[Replied_By] [varchar](70) NOT NULL

INSERT INTO Personal.Storytext_Activities
VALUES (1,	'In quis justo.',	'PU5'),
       (1,	'In quis justo.',	'PU5'),
        (3,	    'Pellentesque viverra pede ac diam.',	'BU6'),
        (4, 	'Nam dui.',	'PU13'),
        (5,	    'Donec quis orci eget orci vehicula condimentum.',	'BU21'),
        (6,	    'Morbi vel lectus in quam fringilla rhoncus.',	'PU5'),
        (7,	    'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',	'BU2'),
        (8,	    'Curabitur in libero ut massa volutpat convallis.',	'PU15'),
        (9,	    'Maecenas ut massa quis augue luctus tincidunt.',	'BU9'),
        (10,	    'Nulla nisl.',	'BU21'),
        (10,	'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',	'BU3'.),
        (12,    'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',	'PU14'),
        (13,    'Fusce consequat.',	'PU24'),
        (14,	'Donec ut mauris eget massa tempor convallis.',	'PU16'),
        (15,	'Etiam pretium iaculis justo.',	'PU25'),
        (16,	'Lorem ipsum dolor sit amet, consectetuer adipiscing elit',	'BU23'),
        (16,	'Cras pellentesque volutpat dui.',	'BU9'),
        (18,	'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',	'PU11'),
        (19,	'Curabitur gravida nisi at nibh.',	'PU25'),
        (20,	'Lorem ipsum dolor sit amet, consectetuer adipiscing elit',	'BU21'),
        (21,	'Donec ut dolor.',	'PU4'),
        (5,	'Aenean fermentum.',	'BU14'),
        (23,	'Duis aliquam convallis nunc.',	'BU3'),
        (12,	'Etiam vel augue.',	'PU9'),
        (11,	'Nullam sit amet turpis elementum ligula vehicula consequat.',	'PU24'),
        (5,	'Curabitur at ipsum ac tellus semper interdum.',	'PU10'),
        (8,	'Curabitur at ipsum ac tellus semper interdum.',	'BU20'),
        (17,	'Aliquam sit amet diam in magna bibendum imperdiet',	'PU22'),
        (14,	'Etiam pretium iaculis justo.',	'PU5'),
        (10,	'Ut tellus.',	'PU25'),
        (16,	'Suspendisse accumsan tortor quis turpis.',	'PU21'),
        (20,	'In quis justo',	'BU5'),
        (2,	'In hac habitasse platea dictumst.',	'BU18'),
        (7,	'In quis justo.',	'PU5'),
        (8,	'Pellentesque viverra pede ac diam.',	'PU11'),
        (9,    'Nam dui.',	'PU19'),
        (11,	'Morbi vel lectus in quam fringilla rhoncus.',	'BU24'),
        (12,	'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',	'PU22'),
        (21,	'Nulla nisl.',	'BU7'),
        (10,	'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',	'BU3'),
        (21,	'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',	'PU13'),
        (4,	'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',	'PU1'),
        (16,	'Cras pellentesque volutpat dui.',	'BU9'),
        (20,	'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede',	'BU14'),
        (19,	'Curabitur gravida nisi at nibh.',	'PU25'),
        (9,	'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',	'BU25'),
        (21,	'Donec ut dolor.',	'PU14')



